### PR TITLE
Embed snoo hydraulic press youtube video to 503 page

### PR DESCRIPTION
**Pull request by birakattack**
Just used the youtube embed script to put the video on the 503 page. 

:eyeglasses: @spladug @spez 

P.S. Snoo can attack at any time!

### CODE REVIEW

**Comment by spez** [comment]
sweet! demo?

**Comment by birakattack** [comment]
What would be the best way to demo this? Not really sure how this repo fits into the whole deployment.

**Comment by spez** [comment]
me neither... push it onto your staging and hope for the best?

**Comment by spladug** [comment]
it's just a static file that gets served directly from haproxy. i've just popped it up on s3 so we can see it in a browser: http://reddit.s3.amazonaws.com/503.html

do we want to be linking the youtube video directly? (will that cause any issues with them?) otherwise looks good to me.

**Comment by spez** [comment]
well hopefully we're not driving too much traffic...

**Comment by powerlanguage** [comment]
lol.

i think this might work better if it replaced the cat image entirely.

**Comment by birakattack** [comment]
@spez @powerlanguage - Should we replace the Snoo image with the video or is it fine the way that it is?

**Comment by spez** [comment]
I trust you all to make this critical decision on your own

**Comment by spladug** [comment]
:runner: i'll let y'all decide on the look of the page. feel free to summon me back for deploy.

**Comment by birakattack** [comment]
Killing this as its old

**Pull request closed without merging**
